name: DeeperWorld
version: ${plugin_version}
main: com.mineinabyss.deeperworld.DeeperWorldPlugin
authors: [Derongan, Offz, Boy000, Norazan, Scyu]
api-version: '1.21'
description: A plugin for letting you create a deeper world. Or at least fake it.

softdepend: [BlockLocker, FastAsyncWorldEdit]

permissions:
  deeperworld.*:
    description: Gives access to all commands
    children:
      deeperworld.admin: true
  deeperworld.admin:
    description: Have power to use admin comands
    default: op

dependencies:
  server:
    Idofront:
      required: true
      load: BEFORE
      join-classpath: true
    BlockLocker:
      required: false
      load: BEFORE
      join-classpath: true
    FastAsyncWorldEdit:
      required: false
      load: BEFORE
      join-classpath: true
