name: DeeperWorld
version: ${plugin_version}
main: com.derongan.minecraft.deeperworld.DeeperWorld
authors: [Derongan]
api-version: '1.16'
description: A plugin for letting you create a deeper world. Or at least fake it.

softdepend: [Multiverse-Core, BlockLocker, KotlinSpice, ProtocolLib, FastAsyncWorldEdit, Geary]

commands:
  deeperworld:
    aliases: [ dw ]
  linfo: {}

permissions:
  deeperworld.*:
    description: Gives access to all commands
    children:
      deeperworld.admin: true
  deeperworld.admin:
    description: Have power to use admin comands
    default: op