name: DeeperWorld
version: ${plugin_version}
main: com.mineinabyss.deeperworld.DeeperWorldPlugin
authors: [Derongan, Offz, Boy000, Norazan, Scyu]
api-version: '1.17'
description: A plugin for letting you create a deeper world. Or at least fake it.

softdepend: [Multiverse-Core, BlockLocker, KotlinSpice, ProtocolLib, FastAsyncWorldEdit, Geary]

commands:
  deeperworld:
    aliases: [ dw ]

permissions:
  deeperworld.*:
    description: Gives access to all commands
    children:
      deeperworld.admin: true
  deeperworld.admin:
    description: Have power to use admin comands
    default: op
